In [1]:
# Imports and settings:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 4)

In [2]:
example_input = pd.read_csv('sample_input.csv', index_col=0, header=0)
# (the left-most index values are unique ids identifying the reaction rows)

example_input  # (truncated view)

,reactant_1_name,reactant_1_mass,...,exchanged_groups_VIA,exchanged_groups_VIIA
1824,CH,13.019,...,0.0,0.0
409,H+,1.008,...,0.0,0.0
4506,C2H2,26.038,...,0.0,0.0
4012,C2+,24.022,...,0.0,0.0
3657,H2O+,18.015,...,0.0,0.0
2286,CH2,14.027,...,0.0,0.0
1679,C+,12.011,...,0.0,0.0
8935,C8,96.088,...,0.0,0.0
1424,C+,12.011,...,0.0,0.0
6912,Ar+,39.950,...,0.0,0.0

In [3]:
np.array(example_input.columns)

array(['reactant_1_name', 'reactant_1_mass', 'reactant_1_charge',
       'reactant_1_hform', 'reactant_1_hform_neutral',
       'reactant_1_polarizability', 'reactant_1_dipole_moment',
       'reactant_2_name', 'reactant_2_mass', 'reactant_2_charge',
       'reactant_2_hform', 'reactant_2_hform_neutral',
       'reactant_2_polarizability', 'reactant_2_dipole_moment',
       'product_1_name', 'product_1_mass', 'product_1_charge',
       'product_1_hform', 'product_1_hform_neutral',
       'product_1_polarizability', 'product_1_dipole_moment',
       'product_2_name', 'product_2_mass', 'product_2_charge',
       'product_2_hform', 'product_2_hform_neutral',
       'product_2_polarizability', 'product_2_dipole_moment',
       'exchanged_mass', 'exchanged_atoms', 'lhs_mu', 'rhs_mu',
       'lhs_charge_00', 'lhs_charge_+0', 'lhs_charge_+-', 'rhs_charge_00',
       'rhs_charge_+0', 'reactant_1_blocks_s', 'reactant_1_blocks_p',
       'reactant_2_blocks_s', 'reactant_2_blocks_p', 'product_1_blocks_s',
       'product_1_blocks_p', 'product_2_blocks_s', 'product_2_blocks_p',
       'exchanged_blocks_s', 'exchanged_blocks_p', 'reactant_1_groups_IA',
       'reactant_1_groups_IVA', 'reactant_1_groups_VA',
       'reactant_1_groups_VIA', 'reactant_1_groups_VIIA',
       'reactant_2_groups_IA', 'reactant_2_groups_IVA',
       'reactant_2_groups_VA', 'reactant_2_groups_VIA',
       'reactant_2_groups_VIIA', 'product_1_groups_IA',
       'product_1_groups_IVA', 'product_1_groups_VA',
       'product_1_groups_VIA', 'product_1_groups_VIIA',
       'product_2_groups_IA', 'product_2_groups_IVA',
       'product_2_groups_VA', 'product_2_groups_VIA',
       'product_2_groups_VIIA', 'exchanged_groups_IA',
       'exchanged_groups_IVA', 'exchanged_groups_VA',
       'exchanged_groups_VIA', 'exchanged_groups_VIIA'], dtype=object)

In [4]:
# import the trained regression model:
from utils import get_final_regression_pipeline
regression_model = get_final_regression_pipeline()

# predict the reaction rate coefficients for the 10 reactions
# described by the example_input DataFrame:
k_predicted = regression_model.predict(example_input)

k_predicted

array([1.18797400e-09, 5.29729997e-09, 9.87500861e-11, 3.15630581e-10,
       1.89232973e-09, 8.37593678e-10, 6.48672484e-08, 1.77991274e-09,
       9.38216266e-10, 1.66151833e-10])